# Generated by Django 3.0.5 on 2020-05-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=50)),
                ('content', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(default='4', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='course',
            name='chapters',
            field=models.ManyToManyField(to='course.Chapter'),
        ),
    ]
