# Generated by Django 3.0.5 on 2020-05-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='owner',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
