# Generated by Django 3.0.5 on 2020-05-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_chapter_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.IntegerField(),
        ),
    ]
