# Generated by Django 3.0.5 on 2020-06-30 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200630_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^[\\w\\W]+$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
