# Generated by Django 3.0.5 on 2020-07-01 23:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_auto_20200701_0223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Posts',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='message',
            new_name='post',
        ),
    ]
